#!/bin/bash

# Taken from swarminglogic.com
#
# Watch over project files, and automatically rebuild
# project when files are modified. Can easily be
# customized for different project types/languages.
#
# Use: ./autobuild.sh [executable]
#
# Optional: Pass path to executable to run whenever
#           build succeeds.
#
# e.g.  ./autobuild.sh bin/main
#

command='find $1
 -name "[!\.]*.cpp" -or
 -name "[!\.]*.h" -or
 -name "[!\.]*.cc" -or
 -name "[!\.]*.cxx"
 | xargs stat -c %y | md5sum'

compileCommand=$2
lgreen='\033[01;32m'
red='\033[00;31m'
restore='\033[0m'

# ----------------------------------------

md5sumStart=`eval $command`
clear
echo "Waiting for changes to ${3}."

while [[ true ]]
do
    md5sumNow=$md5sumStart

    # Loop until some files have changed
    while [[ "$md5sumNow" = "$md5sumStart" ]]
    do
        sleep 0.5
        md5sumNow=`eval $command`
    done

    # Recompile
    clear
    $compileCommand
    compiled=$?
    md5sumStart=`eval $command`

    # Report build ok, or failure (clear if former)
    if [[ $compiled -eq 0 ]]
    then
        clear
        echo -e "[${lgreen} $3 Build OK ${restore}]"
    else
        echo -e "[${red} $3 Build Failed ${restore}]"
    fi
done
