#!/bin/bash
# print a message in a color, mostly used for exit_status when watch-ing something
source colors

# usage: status [string] [color]
function status () {
  echo -e "${2} ${1} ${Color_Off}"
}
function exit_status () {
 if [ $2 == 0 ] ;  then
  status "${1}" ${IGreen}
 else
  status "${1}" ${IRed}
 fi
}
