#!/bin/bash

tmux new-session -d -s autobuild -n build
tmux split-window -h

tmux select-pane -t 0
tmux send-keys 'cd $DEVROOT/bio/scripts && ./autobuild.sh' C-m
tmux select-pane -t 1
tmux send-keys 'cd $DEVROOT/amsi/scripts && ./autobuild.sh' C-m