#!/bin/bash

tmux new-session -d -s bio -n dev
tmux select-pane -t 0
tmux send-keys 'cd ${DEVROOT}/biotissue && svn update .' C-m
tmux send-keys 'select_random_file $DEVROOT/biotissue/macro/src $DEVROOT/biotissue/micro_fo/src' C-m
