macro(describeVar varName)
  message(STATUS "${varName} : ${${varName}}")
endmacro(describeVar varName)

macro(getEnv varName)
  set(varName $ENV{${varName}})
endmacro(getEnv varName)

macro(emptyTest varName isEmptyName)
  if("${${varName}}" STREQUAL "")
    set(${isEmptyName} TRUE)
  else("${${varName}}" STREQUAL "")
    set(${isEmptyName} FALSE)
  endif("${${varName}}" STREQUAL "")
endmacro(emptyTest varName isEmptyName)

macro(checkSetParam varName isRequired)
  message(STATUS "checking for configure parameter ${varName}")
  describeVar(${varName})
  emptyTest(${varName} isEmpty)
  if(${isEmpty})
    getEnv(${varName})
    emptyTest(${varName} isEmpty)
    if(${isEmpty})
      if(${isRequired})
        message(FATAL_ERROR 
                "${varName} is not defined or in the environment, please specify ${varName}")
      else(${isRequired})
        message(SEND_ERROR "${varName} not found")
      endif(${isRequired})
    endif(${isEmpty})
  endif(${isEmpty})
  describeVar(${varName})
endmacro(checkSetParam varName)

macro(prependList lst prfx nwlst)
  foreach(itm ${lst})
    list(APPEND ${nwlst} ${prfx}${itm})
  endforeach()
endmacro()