macro(describeVar varName)
  message(STATUS "${varName} : ${${varName}}")
endmacro(describeVar varName)

macro(describeEnvVar varName)
  message(STATUS "ENV{${varName}} : $ENV{${varName}}")
endmacro(describeEnvVar varName)

macro(getEnv varName)
  set(${varName} $ENV{${varName}})
endmacro(getEnv varName)

macro(emptyTest varName isEmptyName)
  if("${${varName}}" STREQUAL "")
    set(${isEmptyName} TRUE)
  else("${${varName}}" STREQUAL "")
    set(${isEmptyName} FALSE)
  endif("${${varName}}" STREQUAL "")
endmacro(emptyTest varName isEmptyName)

macro(checkSetParam varName isRequired)
  emptyTest(${varName} isEmpty)
  if(${isEmpty})
    getEnv(${varName})
    emptyTest(${varName} isEmpty)
    if(${isEmpty} AND ${isRequired})
      message(FATAL_ERROR
        "${varName} is not defined or in the environment, please specify ${varName}")
    endif(${isEmpty} AND ${isRequired})
  endif(${isEmpty})
  #describeVar(${varName})
endmacro(checkSetParam varName)

macro(prependList lst prfx nwlst)
  foreach(itm ${lst})
    list(APPEND ${nwlst} ${prfx}${itm})
  endforeach()
endmacro()

macro(use_cxx11)
  if(CMAKE_VERSION VERSION_LESS "3.1")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
      set(CMAKE_CXX_FLAGS "--std=gnu++11 ${CMAKE_CXX_FLAGS}")
    else()
      message(STATUS "Unrecognized compiler : ${CMAKE_CXX_COMPILER_ID} C++11 flag not set!")
    endif()
  else()
    set(CMAKE_CXX_STANDARD 11)
  endif()
endmacro(use_cxx11)